CREATE TABLE ARMAZENAMENTO (
ID INT AUTO_INCREMENT PRIMARY KEY,
CAIXA BIGINT NOT NULL,
ID_CLI INT NOT NULL,
ID_UNIDADE INT NOT NULL,
ID_ARMARIO INT NOT NULL,
UNIQUE (CAIXA)
);

CREATE TABLE CLIENTES1 (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLI VARCHAR(255)
);

CREATE TABLE UNIDADE (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_UNIDADE VARCHAR(255)
);

CREATE TABLE ARMARIO (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_ARM VARCHAR(255)
);

ALTER TABLE ARMAZENAMENTO ADD FOREIGN KEY (ID_CLI) REFERENCES CLIENTES1(ID);
ALTER TABLE ARMAZENAMENTO ADD FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID);
ALTER TABLE ARMAZENAMENTO ADD FOREIGN KEY (ID_ARMARIO) REFERENCES ARMARIO(ID);

INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("CAIXAS DE PAPELAO PONTO COM");
INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("CAIXOTES E CIA");
INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("COMERCIO DE EQUIPAMENTOS");
INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("DOCUMENTOS DE CARROS IMPORTADOS");
INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("HOSPITAL DO POVO BRASILEIRO");
INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("INDUSTRIA DE EMBALAGENS");
INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("PAPELARIA DAS COLINAS");
INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("REMEDIOS EMBALADOS");
INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("RH DE QUALIDADE");
INSERT INTO CLIENTES1 (NOME_CLI) VALUES ("SACOLAS E PAPELOES");

INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("SÃO PAULO – CENTRO");
INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("SÃO PAULO – INTERIOR");
INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("SÃO PAULO – ZONA NORTE");
INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("MINAS GERAIS – CENTRO");
INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("MINAS GERAIS – SUL");
INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("CURITIBA – CENTRO");
INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("RIO GRANDE DO SUL – NORTE");
INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("RIO DE JANEIRO – CENTRO-OESTE");
INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("BAHIA – CENTRO");
INSERT INTO UNIDADE (NOME_UNIDADE) VALUES ("AMAZONAS – CENTRO-NORTE");

INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00001");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00002");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00003");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00004");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00005");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00006");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00007");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00008");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00009");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00010");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00011");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00012");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00013");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00014");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00015");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00016");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00017");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00018");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00019");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00020");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00021");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00022");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00023");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00024");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00025");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00026");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00027");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00028");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00029");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00030");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00031");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00032");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00033");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00034");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00035");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00036");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00037");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00038");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00039");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00040");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00041");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00042");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00043");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00044");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00045");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00046");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00047");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00048");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00049");
INSERT INTO ARMARIO (NOME_ARM) VALUES ("PRA-00050");

CREATE TABLE USUARIO (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_USUARIO VARCHAR(255) NOT NULL,
LOGIN VARCHAR(200) NOT NULL,
SENHA VARCHAR(50) NOT NULL
);

INSERT INTO USUARIO (NOME_USUARIO, LOGIN, SENHA) VALUES ("Convidado","convidado","");
INSERT INTO USUARIO (NOME_USUARIO, LOGIN, SENHA) VALUES ("Administrador do Sistema","administrador","");

CREATE TABLE FUNCIONARIOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_FUNC VARCHAR(255),
ID_PROC INT NOT NULL
);

CREATE TABLE PROCEDIMENTOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_PROC VARCHAR(255)
);

CREATE TABLE CLIENTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLI VARCHAR(255) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
DATA DATE NOT NULL,
HORARIO TIME NOT NULL,
ID_PROC INT NOT NULL,
ID_STATUS INT NOT NULL
);

CREATE TABLE STATUS1 (
ID INT  AUTO_INCREMENT PRIMARY KEY,
NOME_STATUS VARCHAR(255) NOT NULL
);

ALTER TABLE CLIENTES ADD FOREIGN KEY (ID_PROC) REFERENCES PROCEDIMENTOS(ID);
ALTER TABLE FUNCIONARIOS ADD FOREIGN KEY (ID_PROC) REFERENCES PROCEDIMENTOS(ID);
ALTER TABLE CLIENTES ADD FOREIGN KEY (ID_STATUS) REFERENCES STATUS1(ID);

INSERT INTO STATUS1 (NOME_STATUS) VALUES ("AGENDADO") ;
INSERT INTO STATUS1 (NOME_STATUS) VALUES ("CANCELADO") ;
INSERT INTO STATUS1 (NOME_STATUS) VALUES ("AGUARDANDO") ;
INSERT INTO STATUS1 (NOME_STATUS) VALUES ("REAGENDAR") ;
INSERT INTO STATUS1 (NOME_STATUS) VALUES ("FALTA") ;
INSERT INTO STATUS1 (NOME_STATUS) VALUES ("ATENDIDO") ;

INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("ESCOVA");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("LAVAGEM");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("CORTE");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("SELAGEM COM FORMOL");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("SELAGEM SEM FORMOL");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("PROGRESSIVA");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("TINTURA");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("MANICURE");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("PEDICURE");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("MANICURE E PEDICURE");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("DEPILACAO");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("PENTEADO");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("MAQUIAGEM");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("DIA DA NOIVA");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("DIA DA DEBUTANTE");
INSERT INTO PROCEDIMENTOS (NOME_PROC) VALUES ("MASSAGEM RELAXANTE");

INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('JOAO BATISTA',1);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('GLORIA TERESA',2);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('ANA CECILIA',3);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('MARIA DAS DORES',4);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('THIFANY DA SILVA',5);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('JESSICA ALVES',6);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('MONICA BASTOS',7);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('JULIANA OLIVEIRA',8);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('GABRIELLA DA SILVA',9);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('MICHELE DOS SANTOS',10);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('AMANDA FERREIRA',11);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('YAMAHAXITA XINXUM',12);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('LUCIANA MENDES',13);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('CAROL HULK',14);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('ELLEN SOARES',15);
INSERT INTO FUNCIONARIOS (NOME_FUNC, ID_PROC) VALUES ('MONIQUE',16);

CREATE TABLE STATUS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_STATUS VARCHAR(255) NOT NULL
);

CREATE TABLE FUNCIONARIO (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_FUNC VARCHAR(255) NOT NULL,
DATA_NASC DATE NOT NULL,
TELEFONE INT (11) NOT NULL,
EMAIL VARCHAR(255),
ID_EMPRESA INT NOT NULL,
ID_CARGO INT NOT NULL,
DATA_ADMISSAO DATE NOT NULL,
DATA_DEMISSAO DATE,
ID_STATUS INT NOT NULL,
VALOR DECIMAL(8,2)
);

CREATE TABLE EMPRESA (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_EMPRESA VARCHAR(255),
CNPJ BIGINT NOT NULL
);

INSERT INTO EMPRESA (NOME_EMPRESA, CNPJ) VALUES ("KELVIN CONSTRUCAO CIVIL LTDA",9999999999999);
INSERT INTO EMPRESA (NOME_EMPRESA, CNPJ) VALUES ("KELVIN LOGISTICA LTDA",9999999999998);

CREATE TABLE CARGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_CARGO VARCHAR(255),
ID_EMPRESA INT NOT NULL
);

ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID);
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_CARGO) REFERENCES CARGOS(ID);
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID);
ALTER TABLE CARGOS ADD FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID);

INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("PEDREIRO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("CARPINTEIRO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("MARCENEIRO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ELETRECISTA",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("AJUDANTE",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("SERRALHEIRO",1);

INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("MOTORISTA",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("MOTOBOY",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("AJUDANTE",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("OPERADOR DE EMPILHADEIRA",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("OPERADOR DE MAQUINAS",2);

INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("GERENTE",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("SUPERVISOR",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ASSISTENTE",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ENCARREGADO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("DIRETOR",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("DONO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("GERENTE",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("SUPERVISOR",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ASSISTENTE",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ENCARREGADO",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("DIRETOR",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("DONO",2);

INSERT INTO STATUS (NOME_STATUS) VALUES ("ATIVO");
INSERT INTO STATUS (NOME_STATUS) VALUES ("DEMITIDO");
INSERT INTO STATUS (NOME_STATUS) VALUES ("AFASTADO");